/*-----------------------------------------------------------------------------
 * Filename: OEM_KBC6064.H
 * Function: OEM_KBC6064.C Prototype Include Definition
 *
 * Copyright (c) 2006-2009, ITE Tech. Inc. All Rights Reserved.
 *---------------------------------------------------------------------------*/
#ifndef OEM_KBC6064_H
#define OEM_KBC6064_H

/*-----------------------------------------------------------------------------
 * External Calling Process
 *---------------------------------------------------------------------------*/
void Cmd_80(void);
void Cmd_81(void);
void Cmd_82(void);
void Cmd_83(void);
void Cmd_84(void);
void Cmd_85(void);
void Cmd_86(void);
void Cmd_87(void);
void Cmd_88(void);
void Cmd_89(void);
void Cmd_8A(void);
void Cmd_8B(void);
void Cmd_8C(void);
void Cmd_8D(void);
void Cmd_8E(void);
void Cmd_8F(void);

void Cmd_90(void);
void Cmd_91(void);
void Cmd_92(void);
void Cmd_93(void);
void Cmd_94(void);
void Cmd_95(void);
void Cmd_96(void);
void Cmd_97(void);
void Cmd_98(void);
void Cmd_99(void);
void Cmd_9A(void);
void Cmd_9B(void);
void Cmd_9C(void);
void Cmd_9D(void);
void Cmd_9E(void);
void Cmd_9F(void);

void Cmd_A0(void);
void Cmd_A2(void);
void Cmd_A3(void);
void Cmd_AF(void);

void Cmd_B0(void);
void Cmd_B1(void);
void Cmd_B2(void);
void Cmd_B3(void);
void Cmd_B4(void);
void Cmd_B5(void);
void Cmd_B6(void);
void Cmd_B7(void);
void Cmd_B8(void);
void Cmd_B9(void);
void Cmd_BA(void);
void Cmd_BB(void);
void Cmd_BC(void);
void Cmd_BD(void);
void Cmd_BE(void);
void Cmd_BF(void);

void Cmd_C0(void);
void Cmd_C1(void);
void Cmd_C2(void);
void Cmd_C3(void);
void Cmd_C4(void);
void Cmd_C5(void);
void Cmd_C6(void);
void Cmd_C7(void);
void Cmd_C8(void);
void Cmd_C9(void);
void Cmd_CA(void);
void Cmd_CB(void);
void Cmd_CC(void);
void Cmd_CD(void);
void Cmd_CE(void);
void Cmd_CF(void);

void Cmd_D5(void);
void Cmd_D6(void);
void Cmd_D7(void);
void Cmd_D8(void);
void Cmd_D9(void);
void Cmd_DA(void);
void Cmd_DB(void);
void Cmd_DC(void);
void Cmd_DD(void);
void Cmd_DE(void);
void Cmd_DF(void);
#if SUPPORTED_KBC_EX
void Cmd_E1(void);
void Cmd_E2(void);
void Cmd_E3(void);
void Cmd_E4(void);
void Cmd_E5(void);
void Cmd_E6(void);
void Cmd_E7(void);
void Cmd_E8(void);
void Cmd_E9(void);
void Cmd_EA(void);
void Cmd_EB(void);
void Cmd_EC(void);
void Cmd_ED(void);
void Cmd_EE(void);
void Cmd_EF(void);
#endif
//-----------------------------------------------------------------------------
#endif