/*-----------------------------------------------------------------------------
 * Filename: OEM_INCLUDE.H
 * Function: ALL OEM Prototype Include Definition
 *
 * Copyright (c) 2006-2009, ITE Tech. Inc. All Rights Reserved.
 *---------------------------------------------------------------------------*/
#ifndef OEM_INCLUDE_H
#define OEM_INCLUDE_H

//-----------------------------------------------------------------------------
#include "PROJECT.H"

//-----------------------------------------------------------------------------
#include "OEM_MEMORY.H"
#include "OEM_BATTERY.H"
#include "OEM_CIR.H"
#include "OEM_EC6266.H"
#include "OEM_FAN.H"
#include "OEM_FUNCTION.H"
#include "OEM_GPIO.H"
#include "OEM_KBC6064.H"
#include "OEM_KBMATRIX.H"
#include "OEM_LED.H"
#include "OEM_MAIN.H"
#include "OEM_PMC2.H"
#include "OEM_POWER.H"
#include "OEM_SMBUS.H"

//-----------------------------------------------------------------------------
#endif