/*-----------------------------------------------------------------------------
 * Filename: CORE_INCLUDE.H
 * Function: ALL CORE Prototype Include Definition
 *
 * Copyright (c) 2006-2009, ITE Tech. Inc. All Rights Reserved.
 *---------------------------------------------------------------------------*/
#ifndef CORE_INCLUDE_H
#define CORE_INCLUDE_H

//-----------------------------------------------------------------------------
#include "CORE_MAIN.H"
//-----------------------------------------------------------------------------
#include "CORE_TYPES.H"
#include "CHIP_8032.H"
#include "CHIP_DEF.H"
#include "CHIP_IT723X.H"
#include "CORE_MEMORY.H"

#include "CORE_INIT.H"
#include "CORE_PS2.H"
#include "CORE_HOSTIF.H"
#include "CORE_SCAN.H"
#include "CORE_TIMERS.H"
#include "CORE_SCAN.H"
#include "CORE_SMBUS.H"
#include "CORE_ACPI.H"
#include "CORE_XLT.H"
#include "CORE_PORT6064.H"
#include "CORE_FLASH.H"
#include "CORE_MODULE.H"
#include "CORE_PECI.H"
#include "CORE_HSPI.H"

//-----------------------------------------------------------------------------
#include <intrins.h>
#include <stdio.h>

//-----------------------------------------------------------------------------
#endif